apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - args:
        - server
        - /mnt/azure
        name: minio
        image: minio/minio
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume      
        ports:
        - containerPort: 9000
        env:
        - name: MINIO_ACCESS_KEY
          value: V42FCGRVMK24JJ8DHUYG
        - name: MINIO_SECRET_KEY
          value: bKhWxVF3kQoLY9kFmt91l+tDrEoZjqnWXzY9Eza
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azure-managed-disk      
        
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: LoadBalancer
  ports:
  - port: 9000
  selector:
    app: minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 15Gi

