apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - args:
        - server
        - /data
        name: minio
        image: minio/minio
              
        ports:
        - containerPort: 9000
        env:
        - name: MINIO_ACCESS_KEY
          value: V42FCGRVMK24JJ8DHUYG
        - name: MINIO_SECRET_KEY
          value: bKhWxVF3kQoLY9kFmt91l+tDrEoZjqnWXzY9Eza
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: LoadBalancer
  ports:
  - port: 9000
  selector:
    app: minio
