apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: presto
  name: presto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: presto
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: presto
    spec:
      containers:
      - image: prestosql/presto
        imagePullPolicy: ""
        name: presto
        ports:
        - containerPort: 8080
        resources: {}
      hostname: presto
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
